# -*- coding: utf-8 -*-
"""HR_ANALYTICS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oEh--I5K0GPj07wKqDTDWL526jDmei81
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/sample_data/HR-Employee-Attrition.csv')

df.head()

"""PRINTING ALL COLUMN NAMES

"""

print("all_columns: ",df.columns.tolist())

"""NUMERIC COLUMNS

"""

print("Numeric_columns: ",df.select_dtypes(include='number').columns.tolist())

"""CATEGORICAL COLUMNS"""

print("Categorical: ",df.select_dtypes(include='object').columns.tolist())

"""GETTING DATA INFORMATION"""

df.describe()

df.info()

"""DEALING WITH MISSING VALUES

Check Missing Values
"""

df.isnull().sum()

"""Checking for duplicates

"""

df[df.duplicated()]